// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:655266da-b766-43f6-967a-b105eb9102b8",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_QAfJTIYoW",
    "aws_user_pools_web_client_id": "1edsjrj3ue63lpk6fj5crfore2",
    "aws_mobile_analytics_app_id": "3c6993ab4a6548e89b7b6b8317d807ef",
    "aws_mobile_analytics_app_region": "us-east-1",
    "aws_dynamodb_all_tables_region": "us-east-1",
    "aws_dynamodb_table_schemas": [
        {
            "tableName": "dynamo291db8a3-hyper",
            "region": "us-east-1"
        }
    ],
    "aws_user_files_s3_bucket": "awesomeproject524d79835b6144548c29823a4aad5102-hyper",
    "aws_user_files_s3_bucket_region": "us-east-1",
    "aws_cloud_logic_custom": [
        {
            "name": "TTLOCK",
            "endpoint": "https://r65gwqwtc2.execute-api.us-east-1.amazonaws.com/hyper",
            "region": "us-east-1"
        }
    ]
};


export default awsmobile;
